### ISSUE TITLE
Create a user guide

### ISSUE THREAD

**Issue by dabreegster** [a-b-street/docs#1]
A/B Street (and the other tools) have an overwhelming amount of features, many hard to discover and without adequate in-game explanation. Ideally the UI would be so clear that documentation wouldn't be needed, but until we get there, I think a "user guide" with lots of pictures would be helpful. I half-started one in a Google doc:
![Screenshot from 2021-01-14 09-12-13](https://user-images.githubusercontent.com/1664407/104624571-9907ee80-5648-11eb-90d3-2c8dbc1e67f1.png)
Each section of the guide could focus on "how to use the feature", and there could be an optional hidden-by-default section to explain in a little more technical detail how that thing works. For stop signs, for example, the user guide would explain how to edit them and the rules for people stopping/yielding. The technical would explain the rules for placing them automatically and emphasize that any traffic sign data from OSM isn't used yet.

**Comment by Robinlovelace** [comment]
> I think the best format is to start a separate repo, abstreet-guide or abstreet-book or abstreet-docs, and use mdbook or similar.

Agreed.



> I guess a related question: does it make sense to start a github org for all of the abstreet related repositories?

My 10 cents: certainly!

**Comment by dabreegster** [comment]
Alright, I started a github org, renamed the main repository to a-b-street/abstreet, and started this docs repo. Next steps towards making a user guide:

- possibly re-evaluate mdbook
- bring in some of the user guide drafted at the bottom of https://docs.google.com/document/d/1xb5VW09DgFeNxyMCVYg_uo_torqCBqEE0Uxzl_11OtA/edit?usp=sharing

**Comment by dabreegster** [comment]
Closing this issue because it got off-topic / grew in scope. I'm in the middle of reorganizing the docs/website completely. Anything I don't get to immediately, I'll file an issue to track it properly.
