### ISSUE TITLE
Add edit button

### ISSUE THREAD

**Issue by Robinlovelace** [a-b-street/docs#13]
Inspiration: https://github.com/rust-lang/mdBook/blob/master/guide/book.toml#L14

**Comment by Robinlovelace** [comment]
After the commit above I now see this :tada: 

![image](https://user-images.githubusercontent.com/1825120/128093420-bef98276-c5fb-4b6f-89c1-e6e015e5e75c.png)

**Comment by michaelkirk** [comment]
Nice!

**Comment by dabreegster** [comment]
Hrmm the edit button isn't showing up on the live site. https://a-b-street.github.io/docs/software/index.html

I tried adding `site-url = /docs/`, but although it works when serving locally, not when deployed...

**Comment by michaelkirk** [comment]
It works for me when running locally.

One thing I noticed from the [actions log](https://github.com/a-b-street/docs/runs/3237191774?check_suite_focus=true#step:3:4) which builds the site:
```
mdbook version: 0.3.7
```

Whereas locally I have a newer version:
```
$ mdbook --version
mdbook v0.4.10
```

**Comment by Robinlovelace** [comment]
Looking good! 

![image](https://user-images.githubusercontent.com/1825120/128257058-b79c6a2f-ebc0-4e54-a41d-3ba9a10fb01b.png)
