### ISSUE TITLE
Download link for A/B Street is broken

### ISSUE THREAD

**Issue by Zero3** [a-b-street/docs#24]
The download link for A/B Street on https://a-b-street.github.io/docs/software/abstreet.html points to https://a-b-street.github.io/docs/howto/index.html, which is a page saying "Document not found (404)".

**Comment by dabreegster** [comment]
Thanks for reporting, should be fixed. The docs use mdbook, which both renames README <-> index and has a link checker plugin that doesn't understand this, so testing everything automatically is unfortunately not possible right now. :(
